# Array Mathematics

In [13]:
#import
import numpy as np

In [14]:
# input values
n, m = map(int, input().split())

1 4


In [15]:
# Read  first array
A = np.array([input().split() for _ in range(n)], dtype=int)


1 2 3 4


In [16]:
# Read  second array
B = np.array([input().split() for _ in range(n)], dtype=int)


5 6 7 8


In [17]:
# operations
print(A + B)                  # Addition
print(A - B)                  # Subtraction
print(A * B)                  # Multiplication
print(np.floor_divide(A, B))  # Integer Division (floor division)
print(A % B)                  # Modulus
print(np.power(A, B))         # Power


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
