# Eye and Identity

In [1]:
# imprt 
import numpy as np


In [2]:
# Set print options to match the formatting style of NumPy version 1.13 
np.set_printoptions(legacy='1.13')

In [3]:
# Input  number of rows and columns
n, m = map(int, input().split())

3 3


In [4]:
#  print identity-
print(np.eye(n, m, k=0))


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
