# Floor, Ceil and Rint

In [2]:
#import 
import numpy as np

In [20]:
np.set_printoptions(legacy='1.13')

In [12]:
arr = np.array(input().strip().split(), dtype=float)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


In [21]:
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
