# Shape and Reshape

In [40]:
#import paskages 

import numpy 


In [50]:
#input and split it 
input_num=input().split()

1 2 3 4 5 6 7 8 9


In [51]:
# convert each element to in and strot it in list
list_n=list(map(int , input_num))


In [52]:
#convert list to array
arr=numpy.array(list_n)


In [53]:
#reshape 
print(numpy.reshape(arr ,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
