# Zeros and Ones

In [7]:
import numpy as np

In [16]:
# input   shape of the array
shape = tuple(map(int, input().split()))

3 3 3


In [17]:
shape

(3, 3, 3)

In [18]:
#  array of zeros
zeros_array = np.zeros(shape, dtype=int)


In [19]:
#  array of ones 
ones_array = np.ones(shape, dtype=int)

In [20]:

# Print the arrays
print(zeros_array)
print(ones_array)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
